# version: '3.2'


# Containers

services:
  webapp:
    build: .
    ports:
      - "8080:80"
    networks:
      - net1
    depends_on:
      - sqlserver
    environment:
      - ConnectionStrings:Defualtconnection=Server=sqlserver;Database=MyTestDB;User Id =sa;Password=@Abc123@; Trust Server Certificate =true
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    networks:
      - net1
    # container_name: sqldb
    hostname: sqlserver

    volumes:
      - sqldata:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=@Abc123@

#  Networks :
networks:
  net1: 

# volumes 
volumes:
  sqldata:

